server:
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
  servlet:
    context-path: /event-schedule/v1.0
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/EventsSchedule
    username: postgres
    password: 31121998
    driver-class-name: org.postgresql.Driver
  flyway:
      enabled: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  hibernate:
    ddl-auto: create-drop
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      use_sql_comments: true
  mail:
    host: smtp.gmail.com
    username: <my email>
    password: <my password>
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true